#!/usr/bin/env python

import rpi_gige_v_framework as gige
import cv2
import sys

def main():
    camera_list=gige.GigE_V_VideoCapture.get_camera_list()
    print(camera_list)
    
    camera_id=0
    if (len(sys.argv) >= 2):
        camera_id=sys.argv[1]                
        try:
            camera_id=int(camera_id)
        except: pass
    
    cam=gige.GigE_V_VideoCapture()
    cam.open(camera_id)
    
    for i in range(3):
        #Dump a few frames after open to clear buffers
        cam.read()
    
    res, img=cam.read()    
    if (res):
        cv2.imshow('',img)
        cv2.waitKey()
        cv2.destroyAllWindows()
    cam.release()

if __name__ == '__main__':
    main()